# Generates the verified DATRAS schema table (`datras_schema`, internal package data) from
# live, independently-checkable sources -- the concrete "next step" flagged in
# data-raw/datras_operation_types.R's own header. See AGENTS.md's "Authoritative schema
# project" section for the full story and the standing decisions this build follows.
#
# PHASE A ONLY (2026-07-23): builds the table and a diagnostic diff report against today's
# getDatrasFieldList(). Does NOT wire anything into applyDatrasTypeSchema()/
# applyDatrasNameSchema() -- that remains a deliberate follow-up, done only after the diff
# report below has been reviewed.
#
# Column provenance -- each column is sourced from whichever input is actually independently
# verifiable for it, not from one single "replacement" table:
#
#   DataFormat, FieldNameOld -- the per-operation WSDL page (data-raw/datras_operation_types.R).
#     Independently authoritative: generated by ASP.NET directly from the operation's real
#     server-side return type, so it cannot drift from reality the way a hand-maintained table
#     can. This is the part that actually fixes bugs (e.g. CPUEL/CPUEA's `Area`, wrongly "int"
#     in getDatrasFieldList() but proven "string" here and by real EVHOE 2001 Q4 data).
#
#   FieldName, Description -- today's getDatrasFieldList() (hot-fix included, as-is). There is
#     NO live server oracle for "new" (English) names covering HH/CA/FL/LT/IDX/CPUEL/CPUEA
#     (only HL has a true independent cross-check: the getHLdataNewHeaders operation) -- a
#     new_names=TRUE/FALSE dual call was tested and found CIRCULAR (applyDatrasNameSchema()
#     derives the "new" name FROM getDatrasFieldList() itself, so it just mirrors this same
#     table). So FieldName/Description are relocated from the existing table, not re-derived.
#     Where a WSDL-crawled old name has no match there, self-map (FieldName = FieldNameOld).
#
#   DescriptionNew -- icesDatras's OWN hand-maintained content
#     (data-raw/datras_field_descriptions.csv), keyed on RecordHeader/FieldNameOld. Two
#     layers, both fully self-contained in this repo:
#       (a) Hand-authored analytical text (practical usage/gotchas -- join-order
#           requirements, "silent error" warnings, grouping-key membership, etc.), not
#           mechanically derivable from any API. One-time ported from obus's hand-curated
#           dr_lookup_fields$description_new on 2026-07-23 (obus/data-raw/
#           DATASET_lookup_fields.R) -- a point-in-time copy, not an ongoing sync. Maintained
#           directly in this file from now on; obus reads FROM icesDatras if it wants this
#           content, not the reverse.
#       (b) Code-value meanings for vocabulary-controlled fields, derived independently via
#           icesVocab (data-raw/datras_vocabulary.R), appended to (a) where a small enough
#           vocabulary resolves -- see step 4b below.
#     Falls back to Description where (a) is blank for a row (see step 3).
#
#   Comment -- an upstream-action-needed worklist, not general notes: flags rows where
#     something needs fixing in ICES's field list, icesVocab, or the DATRAS webserver
#     itself (e.g. the AphiaID/Valid_Aphia overrides below, or an icesVocab/live-data
#     mismatch found while resolving a vocabulary in step 4b).
#
# Fully self-contained (2026-07-23): this script has NO runtime dependency on obus (or any
# other sibling repo) being checked out, present, or in any particular state -- it originally
# read obus/data/dr_lookup_fields.rda live, then a committed snapshot of it, before the
# decision above to make DescriptionNew icesDatras's own permanent content instead of a
# pass-through of obus's. icesVocab (step 4b) is a direct, independent icesDatras dependency
# (already listed in DESCRIPTION's Suggests), not a proxy for obus either.

devtools::load_all(".", quiet = TRUE)
source("data-raw/datras_operation_types.R")

## 1. RecordHeader -> live WSDL operation, verified live 2026-07-23 -----------------------
## (...Sp species-filtered variants of HL/CA share their base operation's return schema --
## no need to crawl them separately. LT's own R function calls the litter-assessment
## operation under a different name than its RecordHeader label -- confirmed by reading
## R/getLTassessment.R directly, not assumed.)

record_operations <- c(
  HH    = "getHHdata",
  HL    = "getHLdata",
  CA    = "getCAdata",
  FL    = "getFlexFile",
  LT    = "getLitterAssessmentOutput",
  IDX   = "getIndices",
  CPUEL = "getCPUELength",
  CPUEA = "getCPUEAge"
)

## 2. Crawl WSDL types + old names for each RecordHeader ----------------------------------
## Type vocabulary confirmed live across all 8 operations before writing this map: only
## string/int/decimal/float appear. "float" gets the same char/int/decimal normalisation
## getDatrasFieldList()'s own hot-fix already applies to the upstream table.

wsdl_type_map <- c(
  string  = "char",
  int     = "int",
  decimal = "decimal",
  float   = "decimal"
)

map_wsdl_type <- function(x) {
  unknown <- setdiff(unique(x), names(wsdl_type_map))
  if (length(unknown) > 0) {
    stop("Unmapped WSDL type(s): ", paste(unknown, collapse = ", "),
         " -- add to wsdl_type_map in data-raw/build_datras_schema.R before proceeding.",
         call. = FALSE)
  }
  unname(wsdl_type_map[x])
}

message("Crawling WSDL operation pages for ", length(record_operations), " operations...")
valid_ops <- get_datras_operations()

crawled <- do.call(rbind, lapply(names(record_operations), function(rh) {
  d <- get_datras_operation_types(record_operations[[rh]], valid_operations = valid_ops)
  data.frame(
    RecordHeader = rh,
    FieldNameOld = d$field,
    DataFormat   = map_wsdl_type(d$type),
    stringsAsFactors = FALSE
  )
}))
row.names(crawled) <- NULL

## 3. Join FieldName/Description from today's getDatrasFieldList() (hot-fix included) ------

fl <- getDatrasFieldList()
fl <- fl[fl$RecordHeader %in% names(record_operations),
         c("RecordHeader", "FieldNameOld", "FieldName", "Description")]
if (anyDuplicated(fl[c("RecordHeader", "FieldNameOld")])) {
  warning("getDatrasFieldList() has duplicate RecordHeader/FieldNameOld rows for these ",
          "RecordHeaders -- keeping first match only.")
  fl <- fl[!duplicated(fl[c("RecordHeader", "FieldNameOld")]), ]
}

fieldlist_match <- match(paste(crawled$RecordHeader, crawled$FieldNameOld),
                          paste(fl$RecordHeader, fl$FieldNameOld))
crawled$FieldName   <- ifelse(is.na(fieldlist_match), crawled$FieldNameOld,
                               fl$FieldName[fieldlist_match])
crawled$Description <- ifelse(is.na(fieldlist_match), "", fl$Description[fieldlist_match])
crawled$has_distinct_new_name <- crawled$FieldName != crawled$FieldNameOld

## 4. Join DescriptionNew from icesDatras's own hand-maintained descriptions ---------------
## Reads data-raw/datras_field_descriptions.csv -- icesDatras's own permanent content (see
## the header note above on its provenance). No obus dependency, live or otherwise.

dlf <- read.csv("data-raw/datras_field_descriptions.csv", stringsAsFactors = FALSE,
                 na.strings = "")
field_desc_match <- match(paste(crawled$RecordHeader, crawled$FieldNameOld),
                          paste(dlf$RecordHeader, dlf$FieldNameOld))
crawled$DescriptionNew <- dlf$DescriptionNew[field_desc_match]

## DescriptionNew is an improvement over Description where this file has one -- but where it
## doesn't (no matching row, or a row with no text), fall back to Description here rather
## than leaving downstream code to do the coalesce itself. DescriptionNew should always be
## the single best-available description, never blank when Description isn't.
crawled$DescriptionNew <- ifelse(is.na(crawled$DescriptionNew), crawled$Description, crawled$DescriptionNew)

## Comment: NOT a general scratchpad. Its one purpose is to flag rows where something is
## known to need fixing UPSTREAM (ICES's own field list, icesVocab, or the DATRAS webserver
## itself) -- i.e. a worklist, not commentary. The AphiaID/Valid_Aphia overrides above are
## exactly this category (documented there). Populated ad hoc below as such cases are found;
## most rows will have none.
crawled$Comment <- NA_character_
idx_plusgr <- crawled$RecordHeader == "IDX" & crawled$FieldNameOld == "PlusGr"
crawled$Comment[idx_plusgr] <- paste(
  "UPSTREAM FLAG (icesVocab, 2026-07-23): icesVocab's own PlusGr vocabulary lists only two",
  "valid values, '+' (age plus group) and '-9' (no plus group) -- but a live getIndices()",
  "pull (NS-IBTS 1965 Q1, species 126417) returned a raw PlusGr value of '5', matching",
  "neither. Likely cause: obus's icesVocab join (DATASET_vocabulary.R) matches by raw field",
  "name only, with no RecordHeader scoping, so CA's flag-style PlusGr vocabulary may be",
  "getting applied to IDX's different, numeric PlusGr field that just shares the same raw",
  "XML tag name. Not resolved here -- flagged as its own follow-up."
)

datras_schema <- crawled[, c("RecordHeader", "FieldNameOld", "FieldName", "DataFormat",
                              "has_distinct_new_name", "Description", "DescriptionNew",
                              "Comment")]

## 4b. Deliberate, documented overrides ----------------------------------------------------
## Not a return to hand-maintaining the whole table -- narrow, justified exceptions only,
## each requiring (a) domain knowledge fixing the true type and (b) live-data confirmation
## that coercion never destroys a value (see AGENTS.md "Authoritative schema project").
##
## IDX's AphiaID: WSDL-declared "char", but CPUEL/CPUEA's WSDL declares the identical WoRMS
## concept "int" -- a same-server inconsistency, not a reflection of the data. Live-checked
## 2026-07-23: 5 real getIndices()/getCPUELength()/getCPUEAge() pulls across 3 surveys and
## 26+ species, every AphiaID value a clean integer, zero exceptions. Also matches the
## pre-Phase-B hot-fix's own IDX AphiaID = "int" and obus's independent dictionary. Needed
## now specifically because Phase B's record= fix (2026-07-23) makes getIndices() correctly
## RecordHeader-scoped to only IDX's own rows -- without this override that fix would regress
## AphiaID from (accidentally correct) int to (WSDL-literal but wrong) char.
override_idx_aphia <- datras_schema$RecordHeader == "IDX" & datras_schema$FieldNameOld == "AphiaID"
datras_schema$DataFormat[override_idx_aphia] <- "int"
datras_schema$Comment[override_idx_aphia] <- paste(
  "Overridden from WSDL-literal 'char' to 'int' 2026-07-23: WoRMS AphiaID is definitionally",
  "numeric; CPUEL/CPUEA's own WSDL declares this field int; live data (5 samples, 3 surveys,",
  "26+ species) never showed a non-integer value; matches the pre-Phase-B hot-fix and obus's",
  "independent dictionary. See AGENTS.md's 'Authoritative schema project' section."
)

## HL/CA's Valid_Aphia: WSDL-declared "char" for both (unlike AphiaID above, HL and CA agree
## with each other here -- no internal WSDL inconsistency to point to). Overridden anyway,
## for a different reason: the pre-Phase-B hot-fix already shipped this as "int" (db_extra
## block in getDatrasFieldList()), so leaving it "char" would be a live regression relative to
## yesterday's behaviour, not just a cosmetic inconsistency with AphiaID. Live-checked
## 2026-07-23: NS-IBTS 2022 Q1 HL (183 distinct values) and CA, zero non-numeric values in
## either. Same WoRMS-ID reasoning as AphiaID above, weaker internal-inconsistency evidence,
## but the regression risk alone justifies it.
override_valid_aphia <- datras_schema$FieldNameOld == "Valid_Aphia" & datras_schema$RecordHeader %in% c("HL", "CA")
datras_schema$DataFormat[override_valid_aphia] <- "int"
datras_schema$Comment[override_valid_aphia] <- paste(
  "Overridden from WSDL-literal 'char' to 'int' 2026-07-23: same WoRMS-ID reasoning as IDX's",
  "AphiaID override, though HL and CA's WSDL agree with each other here (weaker evidence of a",
  "server-side inconsistency). Applied mainly because the pre-Phase-B hot-fix already shipped",
  "this as int -- leaving it char would regress existing behaviour, not just look inconsistent.",
  "Live data (HL 183 distinct values, CA sample) showed zero non-integer values."
)

## 5. Diagnostic diff report vs today's getDatrasFieldList() -------------------------------
## Five categories, stacked into one report for a single review pass:
##   type_mismatch                     -- present in both, but DataFormat disagrees
##   new_wsdl_field_not_in_fieldlist   -- WSDL has it, getDatrasFieldList() doesn't (self-mapped)
##   in_fieldlist_not_in_wsdl          -- getDatrasFieldList() has it, WSDL doesn't (possible
##                                         stale/removed field -- needs a manual look)
##   cross_recordheader_name_mismatch -- the SAME raw field renames differently across
##                                         RecordHeaders (e.g. GearEx -> GearExceptions for
##                                         HH/HL/CA, but LT keeps GearEx self-mapped) --
##                                         doesn't need a live WSDL call, just a self-consistency
##   cross_recordheader_type_mismatch -- the SAME raw field has a different WSDL-declared
##                                         DataFormat across RecordHeaders (e.g. AphiaID is
##                                         "int" for CPUEL/CPUEA but "char" for IDX) -- a
##                                         candidate list for documented, evidence-checked
##                                         overrides, not a verdict by itself.
##                                         check over the table already built above.

make_diff_rows <- function(record_header, field_name_old, diff_type, field_name = NA_character_) {
  data.frame(
    RecordHeader         = record_header,
    FieldNameOld         = field_name_old,
    DataFormat           = rep(NA_character_, length(record_header)),
    DataFormat_fieldlist = rep(NA_character_, length(record_header)),
    FieldName            = rep(field_name, length.out = length(record_header)),
    diff_type            = rep(diff_type, length(record_header)),
    stringsAsFactors = FALSE
  )
}

fl_types <- getDatrasFieldList()
fl_types <- fl_types[fl_types$RecordHeader %in% names(record_operations),
                     c("RecordHeader", "FieldNameOld", "DataFormat")]
names(fl_types)[3] <- "DataFormat_fieldlist"

type_disagreements <- merge(
  datras_schema[c("RecordHeader", "FieldNameOld", "DataFormat")],
  fl_types,
  by = c("RecordHeader", "FieldNameOld")
)
type_disagreements <- type_disagreements[
  type_disagreements$DataFormat != type_disagreements$DataFormat_fieldlist, ]
type_disagreements$FieldName <- NA_character_
type_disagreements$diff_type <- "type_mismatch"

new_discoveries <- make_diff_rows(
  datras_schema$RecordHeader[is.na(fieldlist_match)],
  datras_schema$FieldNameOld[is.na(fieldlist_match)],
  "new_wsdl_field_not_in_fieldlist"
)

stale_idx <- !(paste(fl$RecordHeader, fl$FieldNameOld) %in%
                 paste(datras_schema$RecordHeader, datras_schema$FieldNameOld))
stale_candidates <- make_diff_rows(
  fl$RecordHeader[stale_idx], fl$FieldNameOld[stale_idx], "in_fieldlist_not_in_wsdl"
)

## Same raw field (FieldNameOld), different FieldName across RecordHeaders -- e.g. GearEx
## renames to GearExceptions for HH/HL/CA but stays self-mapped for LT. Pure self-consistency
## check over datras_schema, no live call needed. Restricted to rows with an EXPLICIT
## getDatrasFieldList() entry (fieldlist_match not NA) -- otherwise this just re-flags every
## IDX/CPUEL/CPUEA row that self-mapped for lack of any getDatrasFieldList() coverage at all,
## which new_wsdl_field_not_in_fieldlist already reports; that's not a fresh finding.
matched_only <- datras_schema[!is.na(fieldlist_match), ]
name_by_field <- split(matched_only$FieldName, matched_only$FieldNameOld)
inconsistent_fields <- names(name_by_field)[vapply(name_by_field,
                                                     function(x) length(unique(x)) > 1, logical(1))]
inconsistent_rows <- matched_only[matched_only$FieldNameOld %in% inconsistent_fields, ]
cross_recordheader_mismatches <- make_diff_rows(
  inconsistent_rows$RecordHeader, inconsistent_rows$FieldNameOld,
  "cross_recordheader_name_mismatch", inconsistent_rows$FieldName
)

## Same raw field (FieldNameOld), different DataFormat across RecordHeaders -- e.g. AphiaID
## is "int" per the WSDL for CPUEL/CPUEA but "char" per the WSDL for IDX. UNLIKE the name
## check above, this is NOT restricted to matched_only rows: every row's DataFormat comes
## from the WSDL crawl regardless of whether getDatrasFieldList() also covers it, so the
## comparison is meaningful throughout (excluding it would hide exactly the AphiaID case this
## check exists for, since IDX's AphiaID has no getDatrasFieldList() match at all). This
## check doesn't decide which side is right -- it only surfaces candidates for a documented,
## evidence-checked override (see AGENTS.md "Authoritative schema project").
type_by_field <- split(datras_schema$DataFormat, datras_schema$FieldNameOld)
inconsistent_type_fields <- names(type_by_field)[vapply(type_by_field,
                                                         function(x) length(unique(x)) > 1, logical(1))]
inconsistent_type_rows <- datras_schema[datras_schema$FieldNameOld %in% inconsistent_type_fields, ]
cross_recordheader_type_mismatches <- data.frame(
  RecordHeader         = inconsistent_type_rows$RecordHeader,
  FieldNameOld         = inconsistent_type_rows$FieldNameOld,
  DataFormat           = inconsistent_type_rows$DataFormat,
  DataFormat_fieldlist = NA_character_,
  FieldName            = inconsistent_type_rows$FieldName,
  diff_type            = "cross_recordheader_type_mismatch",
  stringsAsFactors = FALSE
)

diff_report <- rbind(type_disagreements, new_discoveries, stale_candidates,
                      cross_recordheader_mismatches, cross_recordheader_type_mismatches)
diff_report <- diff_report[order(diff_report$FieldNameOld, diff_report$RecordHeader), ]
row.names(diff_report) <- NULL

## 5b. icesVocab code-meaning enrichment ---------------------------------------------------
## Appends "Codes: X = ...; Y = ...." to DescriptionNew for fields with a small enough
## icesVocab-resolved vocabulary -- never replacing the hand-authored/fallback text already
## there (step 4). Fully independent of obus: icesVocab is a direct icesDatras dependency
## (already in DESCRIPTION's Suggests). See data-raw/datras_vocabulary.R's header for the
## TS_/AC_ prefix mechanics and why TS_ (Trawl Survey) is preferred over AC_ (Acoustic survey
## -- a different ICES data domain).
##
## Two fields needed hand-verification before trusting their vocabulary here, rather than
## applying it blindly (both live-checked 2026-07-23, via obus::dr_con()):
##   - GearEx: flagged by this build's own cross_recordheader_name_mismatch (LT self-maps,
##     HH/HL/CA rename to GearExceptions) -- but that's a FieldName disagreement, not a vocab
##     one. Checked HH's GearExceptions and LT's GearEx real values: every one observed
##     (R/I2/B/S2/SB/D/S/DB) matches TS_GearEx's vocabulary exactly. Vocabulary is fine;
##     enrich normally.
##   - PlusGr: flagged by cross_recordheader_type_mismatch (CA=char, IDX=decimal) and already
##     has an UPSTREAM FLAG Comment above (icesVocab's "+"/"-9" vocabulary doesn't match
##     IDX's real "5"-style values). Checked CA's real AgePlusGroup values: exactly "+"/NA,
##     matching TS_PlusGr's vocabulary exactly. So the vocabulary IS correct for CA, just not
##     IDX -- a genuine per-RecordHeader exception, not a global skip.

source("data-raw/datras_vocabulary.R")

VOCAB_CODE_LIMIT <- 20  # fields with more codes than this are left unenriched (e.g.
                        # Survey=133, StatRec=7159 codes) -- inlining that many isn't useful
                        # prose; ported/fallback text from step 4 stays as-is for these.

vocab_types <- get_icesvocab_types()

for (field in unique(datras_schema$FieldNameOld)) {
  vocab <- first_usable_vocab(field, vocab_types)
  if (is.na(vocab$key) || nrow(vocab$codes) == 0 || nrow(vocab$codes) > VOCAB_CODE_LIMIT) next

  code_text <- paste0(
    "Codes: ",
    paste(sprintf("%s = %s", vocab$codes$Key, vocab$codes$Description), collapse = "; "),
    "."
  )

  for (i in which(datras_schema$FieldNameOld == field)) {
    # Verified exception (see note above): PlusGr's vocabulary is confirmed correct for CA
    # but confirmed wrong for IDX -- skip IDX specifically rather than apply a known mismatch.
    if (field == "PlusGr" && datras_schema$RecordHeader[i] == "IDX") next
    datras_schema$DescriptionNew[i] <- paste(datras_schema$DescriptionNew[i], code_text)
  }
}

## 6. Cross-check FieldNameOld completeness against one real live pull per record type -----
## Best-effort only: a transient issue with one specific historical survey/year/quarter
## shouldn't fail the whole build, so this warns rather than stopping.

check_live_columns <- function(label, expr) {
  live <- tryCatch(eval(expr), error = function(e) { message("  (skipped: ", conditionMessage(e), ")"); NULL })
  if (!is.data.frame(live) || nrow(live) == 0) {
    warning("Live cross-check for ", label, " returned no data -- skipped.")
    return(invisible())
  }
  rh <- sub(" .*", "", label)
  wsdl_names <- datras_schema$FieldNameOld[datras_schema$RecordHeader == rh]
  missing_from_wsdl <- setdiff(names(live), wsdl_names)
  if (length(missing_from_wsdl) > 0) {
    warning(label, ": live raw response has columns the WSDL crawl didn't declare: ",
            paste(missing_from_wsdl, collapse = ", "))
  } else {
    message("  ", label, ": all ", ncol(live), " live raw columns found in the WSDL crawl.")
  }
}

message("\nCross-checking WSDL field sets against real live pulls...")
check_live_columns("HH NS-IBTS/2022/Q1",
  quote(getDATRAS("HH", "NS-IBTS", years = 2022, quarters = 1, fix_types = FALSE, new_names = FALSE)))
check_live_columns("HL NS-IBTS/2022/Q1",
  quote(getDATRAS("HL", "NS-IBTS", years = 2022, quarters = 1, fix_types = FALSE, new_names = FALSE)))
check_live_columns("CA NS-IBTS/2022/Q1",
  quote(getDATRAS("CA", "NS-IBTS", years = 2022, quarters = 1, fix_types = FALSE, new_names = FALSE)))
check_live_columns("FL NS-IBTS/2022/Q1",
  quote(getFlexFile("NS-IBTS", 2022, 1, fix_types = FALSE, new_names = FALSE)))
check_live_columns("LT NS-IBTS/2022/Q1",
  quote(getLTassessment("NS-IBTS", 2022, 1, fix_types = FALSE, new_names = FALSE)))
check_live_columns("CPUEL EVHOE/2001/Q4",
  quote(getCPUELength("EVHOE", 2001, 4, fix_types = FALSE, new_names = FALSE)))
check_live_columns("CPUEA EVHOE/2001/Q4",
  quote(getCPUEAge("EVHOE", 2001, 4, fix_types = FALSE, new_names = FALSE)))
check_live_columns("IDX NS-IBTS/1965/Q1",
  quote(getIndices(survey = "NS-IBTS", year = 1965, quarter = 1, species = 126417,
                    fix_types = FALSE, new_names = FALSE)))

## 7. Save ----------------------------------------------------------------------------------

usethis::use_data(datras_schema, internal = TRUE, overwrite = TRUE)
write.csv(diff_report, "data-raw/datras_schema_diff.csv", row.names = FALSE)

message("\ndatras_schema: ", nrow(datras_schema), " rows across ",
        length(unique(datras_schema$RecordHeader)), " RecordHeaders:")
print(table(datras_schema$RecordHeader))
message("\ndescription_new coverage:")
print(tapply(!is.na(datras_schema$DescriptionNew), datras_schema$RecordHeader, sum))
message("\ndiff report: ", nrow(diff_report), " disagreements -> data-raw/datras_schema_diff.csv")
print(diff_report)
